experiment_name: 'diag_all_sim_log'

target: ['Ppar', 'Pper1', 'Pper2']
features: ['rho', 
           'Bx', 'By', 'Bz', 'B_magn', 
           'alpha', 
           'Vx', 'Vy', 'Vz', 
           'dBxdx', 'dBxdy', 'dBydy', 'dBzdx', 'dBzdy']
species: ['all_electrons']
datafiles: ['high_res_2', 'high_res_hbg', 'high_res_bg3', 'high_res_bg0']

outputscaler: null
boxcox: True